api:
  pagination:
    max_per_page: 100
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
  instance:
    instance-id: ${spring.application.name}-${random.int}
    hostname: localhost