api:
  pagination:
    max_per_page: 100
security:
  oauth2:
    resource:
      token-info-uri: http://auth-service/oauth/check_token
    client:
      client-id: oauth2-jwt-client
      client-secret: admin1234
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
  instance:
    instance-id: ${spring.application.name}-${random.int}
    hostname: localhost
logging:
  level:
    root: TRACE