api:
  pagination:
    max_per_page: 100
security:
  oauth2:
    resource:
      prefer-token-info: false
      service-id: auth-service
      token-info-uri: http://localhost:9092/oauth/check_token
      loadBalanced: true
    client:
      client-id: oauth2-jwt-client
      client-secret: admin1234
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/
  instance:
    instance-id: ${spring.application.name}-${random.int}
    hostname: localhost