server:
  port: 9092
spring:
  jpa:
    hibernate:
      show-sql: true
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  jackson:
    time-zone: Asia/Calcutta
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
      resources:
        static-locations: classpath:/static/,file:/d:/hts/sms/assets/
  resources:
    static-locations: classpath:/static/,file:/d:/hts/sms/assets/
logging:
  level:
    org:
      hibernate:
        type: trace
app:
  assetsDir: d:/hts/sms/assets/
