security:
  oauth2:
    resource:
      service-id: auth-service
      token-info-uri: http://localhost:9092/oauth/check_token
    client:
      client-id: oauth2-jwt-client
      client-secret: admin1234
server:
  port: 9093
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/smsaccount?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  jackson:
    servlet:
      resources:
        static-locations: classpath:/static/,file:/d:/hts/sms/assets/
  resources:
    static-locations: classpath:/static/,file:/d:/hts/sms/assets/
logging:
  level:
    org:
      hibernate:
        type: trace
app:
  assetsDir: d:/hts/sms/assets/
