server:
  port: 9092
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/smsaccount?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: false
        format_sql: false
  jackson:
    servlet:
      resources:
        static-locations: classpath:/static/,file:/d:/hts/sms/assets/
  resources:
    static-locations: classpath:/static/,file:/d:/hts/sms/assets/
logging:
  level:
    org:
      hibernate:
        type: trace
app:
  assetsDir: d:/hts/sms/assets/
