security:
  oauth2:
    resource:
      service-id: auth-service
      token-info-uri: http://localhost:9092/oauth/check_token
    client:
      client-id: oauth2-jwt-client
      client-secret: admin1234
server:
  port: 9093
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/smsaccount?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        format_sql: true
        connection:
          characterEncoding: UTF-8
          CharSet: UTF-8
          useUnicode: true
  jackson:
    time-zone: Asia/Calcutta
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
      resources:
        static-locations: classpath:/static/,file:/d:/hts/sms/assets/
  resources:
    static-locations: classpath:/static/,file:/d:/hts/sms/assets/
logging:
  level:
    org:
      hibernate:
        type: trace
app:
  assetsDir: d:/hts/sms/assets/
